# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6aIbDlwlzEEJXqC6SG_wsEHmPyzOapq
"""

# prompt: plot cos downsampling by 2

import numpy as np
import matplotlib.pyplot as plt

# Original signal
fs = 100  # Sampling frequency
t = np.arange(0, 1, 1/fs)
x = np.cos(2 * np.pi * 5 * t)

# Downsampling by a factor of 2
downsampled_x = x[::2]
downsampled_t = t[::2]


# Plotting
plt.figure(figsize=(10, 6))
plt.plot(t, x, label='Original Signal')
plt.plot(downsampled_t, downsampled_x, 'ro-', label='Downsampled Signal')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.title('Cosine Wave Downsampling')
plt.legend()
plt.grid(True)
plt.show()